spring:
  application:
    name: Default-CONFIG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   #this is for MS registered with the server
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
